### ISSUE TITLE
Data for epitope prediction

### ISSUE THREAD

**Issue by leeanapeters** [egarren/scTfh#1]
Hi, thank you for the detailed repository and code!

I was looking to perform a similar analysis to the one you performed with curated TCR data to train and predict on new data. I was wondering how you set up your input data as I just see the master sheet. Did you break this into directories per epitope or antigen as recommended by DeepTCR? I am getting errors that counts should be associated with samples so just wondering how you got around this.

Thanks

Leeana

**Comment by egarren** [comment]
Hello! Yes, the input data should be organized into directories for each antigen or epitope (whichever you're interested in training based on). The code to do this is actually in the `02_vdj.R` file (lines 300-323).

**Comment by leeanapeters** [comment]
Oh I see thanks so much!
